[[./README.org][English README is here]]

* vmc-mixer
複数のVMCPストリームを一つのストリームへミックスします。
複数のツールを用いて一つのモデル(一つのPerformer)を操作したい時
等に便利です。

** 使い方
*** 1. vmc-mixerのバイナリを入手する
[[https://github.com/Cj-bc/vmc-mixer/releases][releases]]ページから各リリース用のバイナリを取得するか、自分でビルドすることができます:

#+begin_src sh
  git clone https://github.com/Cj-bc/vmc-mixer
  cd vmc-mixer
  stack build
#+end_src

*** 2. vmc-mixerを起動する
このレポジトリのルートディレクトリにて ~stack run~ を
走らせると、vmc-mixerを起動することができます。
vmc-mixerをコンパイルした後にTUIが開かれます。

(他のUIは今後追加されると思います)

*** 3. Marionettesとperformersを起動する
vmc-mixerは、受け取ったパケットを ~localhost:39540~ に出力します。
(現在はハードコードされていますが、今後改変可能にする予定です)

なので、使いたいperformerを起動したら、
39540からVMCPメッセージを受け取るように変更してください。
それが難しければ、直接vmc-mixerのコードを改変してもよいです。
(~app/TUI.hs~ にある ~main~ 関数の ~outAddr~ を変えれば良いです)

そして、marionette (モーションデータを作成して送信するソフトウェア)も
起動してください。
複数起動する際、使用するポートが被らないように気をつけてください。

*** 4. 入力のアドレスを追加する
~tab~ キーを押して ~new address editor~ に移動し、入力に使うアドレスを書き込みます。

書き込む際のフォーマットは ~ADDRESS:PORT_NUMBER~ です。

例えば、 ~127.0.0.1~ の 3305ポートから受け取りたい場合は以下の二通りの書き方ができます:

+ ~127.0.0.1:3305~
+ ~localhost:3305~

ドメイン名も使えますが、それが存在するかどうかの判定は行いません。
手元ではIPアドレスと "localhost" のみ動作確認をしています。

*** 5. おわり!動いているはずです
これで動いているはずです。動いていない場合、まずファイヤウォールの設定を確認してください。
使用しようとしているポートがブロックされている可能性があります。

** UI keybind
現在のUIには二つのウィジェットがあります

*** 全体的なキーバインド
いくつかのキーバインドは、どのウィジェットにフォーカスしている時でも使用が可能です。

| Key   | action                           |
|-------+----------------------------------|
| ~Tab~ | 次のウィジェットにフォーカスする |

*** 入力アドレスリスト
上部のウィジェットが入力アドレスリストです。
現在vmc-mixerがメッセージを受け取っている先のアドレスが全て表示されます。

| Key          | action                                 |
|--------------+----------------------------------------|
| ~-~          | 現在選択されているアドレスを削除します |
| ~Up arrow~   | 一つ上を選択します                     |
| ~Down arrow~ | 一つ下を選択します                     |

*** アドレスエディター
下部のウィジェットがアドレスエディターです。
ここにアドレスを書き込んでエンターキーで確定することで、
新しいアドレスを追加できます。

| Key     | action   |
|---------+----------|
| ~Enter~ | 現在入力しているアドレスを確定する |
