[[./README.org][English README is here]]

* vmc-mixer
複数のVMCPストリームを一つのストリームへミックスします。
複数のツールを用いて一つのモデル(一つのPerformer)を操作したい時
等に便利です。

** 使い方
現在2種類のUIが用意されています。

*** 1. vmc-mixerのバイナリを入手する
[[https://github.com/Cj-bc/vmc-mixer/releases][releases]]ページから各リリース用のバイナリを取得するか、自分でビルドすることができます:

#+begin_src sh
  git clone https://github.com/Cj-bc/vmc-mixer
  cd vmc-mixer
  stack build
#+end_src

*** 3. Marionettesとperformersを起動する
使用したいmarionette (モーションデータを受信するソフトウェア)と
Performer(モーションデータを作成して送信するソフトウェア)を
起動してください。
複数起動する際、使用するポートが被らないように気をつけてください。

*** TUI版UIを使用する場合
TUI版は、ターミナルでインタラクティブに操作をすることが可能です。

**** 1. vmc-mixer-tuiを立ち上げる
レポジトリルートで ~stack run vmc-mixer-tui <OUTPUT_ADDRESS>~ で
起動することができます。


**** 2. 入力のアドレスを追加する
~tab~ キーを押して ~new address editor~ に移動し、入力に使うアドレスを書き込みます。

書き込む際のフォーマットは ~ADDRESS:PORT_NUMBER~ です。

例えば、 ~127.0.0.1~ の 3305ポートから受け取りたい場合は以下の二通りの書き方ができます:

+ ~127.0.0.1:3305~
+ ~localhost:3305~

ドメイン名も使えますが、それが存在するかどうかの判定は行いません。
手元ではIPアドレスと "localhost" のみ動作確認をしています。

**** 3. おわり!動いているはずです
これで動いているはずです。動いていない場合、まずファイヤウォールの設定を確認してください。
使用しようとしているポートがブロックされている可能性があります。

*** CLI版UIを使用する場合
CLI版は、インタラクティブな操作を一切提供しません。
起動時のコマンドラインオプションで全て設定する必要があります。
(今後、設定ファイルも追加する予定です)

**** コマンドラインオプション
MarionetteとPerformerを指定する必要があります。

#+begin_src sh
  Usage: vmc-mixer-cli [-i|--inputs ARG] output
#+end_src

例えば、 ~127.0.0.1~ ポート番号 39540と ~127.0.0.1~ ポート番号 39541
から受け取り、 ~192.168.10.10~ ポート番号 39540に送りたい場合、次のようにします:

#+begin_src sh
  vmc-mixer-cli -i 127.0.0.1:39540 -i 127.0.0.1:39541 192.168.10.10:39540
#+end_src

** UI keybind
現在のUIには二つのウィジェットがあります

*** 全体的なキーバインド
いくつかのキーバインドは、どのウィジェットにフォーカスしている時でも使用が可能です。

| Key   | action                           |
|-------+----------------------------------|
| ~Tab~ | 次のウィジェットにフォーカスする |

*** 入力アドレスリスト
上部のウィジェットが入力アドレスリストです。
現在vmc-mixerがメッセージを受け取っている先のアドレスが全て表示されます。

| Key          | action                                 |
|--------------+----------------------------------------|
| ~-~          | 現在選択されているアドレスを削除します |
| ~Up arrow~   | 一つ上を選択します                     |
| ~Down arrow~ | 一つ下を選択します                     |

*** アドレスエディター
下部のウィジェットがアドレスエディターです。
ここにアドレスを書き込んでエンターキーで確定することで、
新しいアドレスを追加できます。

| Key     | action   |
|---------+----------|
| ~Enter~ | 現在入力しているアドレスを確定する |
