[[./JA-README.org][日本語版はこちら]]

* vmc-mixer
Mix several VMCP compatible streams into one stream.
Useful if you want to use number of tools to control one VRM model.

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/d_qsC2fl_Wo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

** Usage
There're two version of UI.

*** 1. Get vmc-mixer binary
You can get binary from [[https://github.com/Cj-bc/vmc-mixer/releases][releases]] page for each release,
or you can build it by yourself:

#+begin_src sh
  git clone https://github.com/Cj-bc/vmc-mixer
  cd vmc-mixer
  stack build
#+end_src

*** 2. Launch your Marionettes and performers
launch your VMC marionette (which receives motion data) and
performers (which sends motion information by VMCP message).
Please launch them with different port number specified.

*** In case you use: TUI (Terminal User Interface)
TUI version have interactive user interface on terminal.

**** 1. Launch vmc-mixer-tui
In this repository root, launch vmc-mixer-tui by ~stack run vmc-mixer-tui <MARIONETTE_ADDRESS>~.
It should compile vmc-mixer-tui and opens TUI.

**** 2. Add input addresses
Focus on ~new address editor~ by pressing ~tab~ key, and type new performer address that
you want vmc-mixer to receive VMCP message from.

The format is ~ADDRESS:PORT_NUMBER~.

For example, if you want to recieve packets from ~127.0.0.1~ by using port 3305,
You can type either:

+ ~127.0.0.1:3305~
+ ~localhost:3305~

It accept domain name, but it doesn't gurantee that is valid.
I only tested IP address and "localhost" domain name by myself.

**** 3. Done! it should be working
It should be working right now.
If it doesn't, please check your firewall settings first.
Those ports might be blocked.

*** In case you use: CLI (Command Line user Interface)
CLI version doesn't have interactive interface at all.
It uses command line options (and config files in the future) instead.


In this repository root, launch vmc-mixer-cli by ~stack run vmc-mixer-cli -- <OPTIONS>~.

***** Command line options
You should specify input/output addresses via command line option.

#+begin_src sh
  Usage: vmc-mixer-cli [-p|--performer ARG] marionette
#+end_src

For example, if you want to recieve packets from ~127.0.0.1~ by using port 39540
and ~127.0.0.1~ port 39541, 
send to ~192.168.10.10~ port 39540, You can do:

#+begin_src sh
  vmc-mixer-cli -i 127.0.0.1:39540 -i 127.0.0.1:39541 192.168.10.10:39540
#+end_src

** UI keybind
Current UI have two widgets.

*** General keybinds
There are some keybindings that is active in
any state.

| Key   | action               |
|-------+----------------------|
| ~Tab~ | focus on next widget |

*** Input Connection list
The widget above is input connection list.
It shows all input addresses available.

| Key          | action                     |
|--------------+----------------------------|
| ~-~          | Remove selected connection |
| ~Up arrow~   | select above               |
| ~Down arrow~ | select below               |

*** New address editor
The widget at bottom is new address editor.
You can use this to insert new address.

| Key     | action              |
|---------+---------------------|
| ~Enter~ | confirm the address |

